services:
  my-server:
    build: .
    ports:
      - 8080:8080
    # my-db의 컨테이너가 생성되고 healthy 하다고 판단 될 때, 해당 컨테이너를 생성한다.
    depends_on:
      my-db:
        condition: service_healthy
      my-cache-server:
        condition: service_healthy

  my-db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pwd123
      MARIADB_DATABASE: mydb  # mariadb 최초 실행 시 mydb 라는 데이터베이스를 생성해준다
    volumes:
      - ./maria_data:/etc/mysql/conf.d
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--user=root", "--password=pwd123", "--database=mydb"]
      interval: 5s  # 5초 간격으로 체크
      retries: 10   # 10번까지 재시도

  my-cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
