version: '3.8'

services:
  jdk:
    container_name: jdk
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd123
      MYSQL_DATABASE: mydb  # mariadb 최초 실행 시 mydb 라는 데이터베이스를 생성해준다
    volumes:
      - ./mysql_data:/etc/mysql/conf.
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--user=root", "--password=pwd123", "--database=mydb" ]
      interval: 5s  # 5초 간격으로 체크
      retries: 10   # 10번까지 재시도

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
