version: '3.8'

services:
  jdk:
    container_name: jdk
    image: openjdk:17-jdk
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  db:
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pwd123
      MARIADB_DATABASE: mydb  # mariadb 최초 실행 시 mydb라는 데이터베이스를 생성해준다
    volumes:
      - ./maria_data:/var/lib/mysql  # 데이터가 저장될 경로 수정
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s  # 5초 간격으로 체크
      retries: 10   # 10번까지 재시도
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    healthcheck:  # 오타 수정
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  maria__data:
