version: '3.8'

services:
  jdk:
    container_name: jdk
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  db:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
        - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
        - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
        - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
        - TZ="Asia/Seoul"
        - ALLOW_EMPTY_PASSWORD=no
        - MARIADB_ROOT_PASSWORD=qwd123
        - MARIADB_USER=root
        - MARIADB_DATABASE=mydb
        - MARIADB_PASSWORD=qwd123
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    healthcheck:  # 오타 수정
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  maria__data:
