spring:
  datasource:
    url: jdbc:mariadb://db:3306/mydb
    username: root
    password: pwd123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: redis
      port: 6379