name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create and set permissions for application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
          chmod 600 ./src/main/resources/application.yml

      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push to docker repo
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/spring_server_image_repository .
          docker push ${{ secrets.DOCKER_REPO }}/spring_server_image_repository

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ubuntu
          key: ${{ secrets.DOCKER_SSH_KEY }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          script: |
            docker compose down  
            docker pull ${{ secrets.DOCKER_REPO }}/spring_server_image_repository
            docker compose up -d --build
            docker image prune -f
          
        
          
        
        
        
        
