name: Deploy To Ubuntu

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh 로 ubuntu 로 접속
        uses: apple boy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/mongta/github-actions-practice
            git pull origin main
            docker-compose down
            docker-compose up -d --build
