name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          cd src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml

      - name: Set file permissions
        run: chmod 600 ./src/main/resources/application.yml

      - name: Build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/spring_server_image_repository .
          docker push ${{ secrets.DOCKER_REPO }}/spring_server_image_repository

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          key: ${{ secrets.DOCKER_SSH_KEY }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          script: |
            sudo docker compose down  
            sudo docker pull ${{ secrets.DOCKER_REPO }}/spring_server_image_repository
            docker compose up -d --build
            docker image prune -f
          
        
          
        
        
        
        
