name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application.yml
      run: |
        cd src\main\resources
        touch ./application.yml
        echo "${{ secrets.APPLICATION_YML }}" > ./application.yml

    - name: Set file permissions
      run: chmod 600 ./src/main/resources/application.yml

    - name: Build with gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test

    - name: Docker build & push to docker repo
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ sercrets.DOCKER_PASSWORD }}
        docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/directors-dev .
        docker push ${{ secrets.DOCKER_REPO }}/directors-dev

    - name: Deploy to server
    - uses: appleboy/ssh-action@master
    - id: deploy
      with:
        host: ${{ secrets.DOCKER_SERVER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        key: ${{ secrets.DOCKER_SSH_KEY }}
        script: |
          sudo docker compose down  
          sudo docker pull ${{ secrets.DOCKER_REPO }}/directors-dev
          docker compose up -d --build
          docker image prune -f
          
        
          
        
        
        
        
